//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsAuthorize
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string UserName { get; set; }
        public bool Admin { get; set; }
    }
}
